### ISSUE TITLE
cleaning of product/website relations not implemented

### ISSUE THREAD

**Issue by ktruehl** [techdivision/import-product#146]
Hello,

The `\TechDivision\Import\Product\Observers\ProductWebsiteUpdateObserver`, while importing new product/website relations perfectly, does not clean out those that are no longer required. For many of the other observers there exist a config setting that indicates whether cleaning should take place or not. Such a feature would be required for the product/website relations as well.

Best regards,
Klaas

**Comment by wagnert** [comment]
This feature has been released with version [3.8.0](https://github.com/techdivision/import-cli-simple/releases/tag/3.8.0).
