### ISSUE TITLE
Update product should not reset created_at and created_in 

### ISSUE THREAD

**Issue by adhocore** [techdivision/import-product#149]
For sku  existing in DB already, if imported using m2if, the `created_at` date should not be reset to new (current) date. I am not very sure of `created_in` field though

**Comment by wagnert** [comment]
@adhocore So far, we assumed that the CSV file contains the `created_at` date, so this wasn't a problem. But you're right, if the `created_at`column is empty, the date should stay untouched. I'll also check the `created_in` field within that context.

**Comment by wagnert** [comment]
@adhocore Has been fixed with release 3.8.6
