### ISSUE TITLE
quantity_and_stock_status value

### ISSUE THREAD

**Issue by adhocore** [techdivision/import-product#155]
QuantityAndStockStatusObserver will always hard reset the value to 1 in this line

https://github.com/techdivision/import-product/blob/23.x/src/Observers/QuantityAndStockStatusObserver.php#L51

should we set the value if only already not given in the input data?

**Comment by wagnert** [comment]
Hi @adhocore This is a copy of techdivision/import#184.

**Comment by adhocore** [comment]
thank you :). wondering if there is some specific reason why we set value to 1. 
looking at techdivision/import#184 seems like we can skip/bypass this.
